### ISSUE TITLE
ImportError: Could not import _ext module.

### ISSUE THREAD

**Issue by Trav1slaflame** [luyh20/VL-Grasp#1]
Hi, team
Thanks for sharing the wonderful project!
I followed the README and successfully configured the env. However, when I was running the Demo by: **python main.py**, I missed this bug:

Traceback (most recent call last):
  File "/home/zhengshen/VL-Grasp/GraspNet/pointnet2/pointnet2_utils.py", line 26, in <module>
    import pointnet2._ext as _ext
ImportError: /home/zhengshen/anaconda3/envs/vlgrasp/lib/python3.7/site-packages/pointnet2-0.0.0-py3.7-linux-x86_64.egg/pointnet2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from engine import grasp_model, vl_model
  File "/home/zhengshen/VL-Grasp/engine.py", line 6, in <module>
    from GraspNet.model.FGC_graspnet import FGC_graspnet
  File "/home/zhengshen/VL-Grasp/GraspNet/model/FGC_graspnet.py", line 21, in <module>
    from pointnet2.pointnet2_utils import CylinderQueryAndGroup
  File "/home/zhengshen/VL-Grasp/GraspNet/pointnet2/pointnet2_utils.py", line 30, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst

It seems that something goes wrong during the pointnet2 compile.
I use python 3.7, pytorch 1.13.0, cuda 11.7.
Could you please help me to compile with this?

**Comment by luyh20** [comment]
Are there any errors when you install the pointnet2 module. I find that I upload an installed version of pointnet2, this may have caused some errors. Maybe you could get the pure version pointnet2 from the [link](https://github.com/luyh20/FGC-GraspNet/tree/main/pointnet2) or remove some files that generated by installing pointnet2,  and reinstall the module.

**Comment by Trav1slaflame** [comment]
Hi, team,
Thank you so much for your reply! I have already solved this bug.

Besides, can you provide the checkpoint weights of the visual grounding **(checkpoint_best_r50.pth)** model and the grasp pose detection **(checkpoint_fgc.tar)** model?

Again, thanks for sharing the wonderful work!

**Comment by luyh20** [comment]
OK，there are Google Drive links, [checkpoint_best_r50.pth](https://drive.google.com/file/d/1HJQKnuiG5J02PZBQJc2KsW3RozmJYH-L/view?usp=sharing) and [checkpoint_fgc.tar](https://drive.google.com/file/d/1x4e23njqi4A_S_LlZPCUHjHT9CqFPzkc/view?usp=sharing).

**Comment by Trav1slaflame** [comment]
> OK，there are Google Drive links, [checkpoint_best_r50.pth](https://drive.google.com/file/d/1HJQKnuiG5J02PZBQJc2KsW3RozmJYH-L/view?usp=sharing) and [checkpoint_fgc.tar](https://drive.google.com/file/d/1x4e23njqi4A_S_LlZPCUHjHT9CqFPzkc/view?usp=sharing).

Received with many thanks
