### ISSUE TITLE
你们的数据存在巨大的问题，请务必重视！！！！！！

### ISSUE THREAD

**Issue by quanfeifan** [luyh20/VL-Grasp#3]
![微信图片_20240312101130](https://github.com/luyh20/VL-Grasp/assets/77908416/6bd426a6-f31a-44d5-8320-79d05354fd8e)
这是你们roborefit的testA那个文件夹的json文件。图中框出来的部分是位置颠倒了，请你们务必重视！！！！！

**Comment by quanfeifan** [comment]
`import cv2
image_path = "D:\\final_dataset\\testA\\image\\0000000.png"
image = cv2.imread(image_path)
x1, y1, x2, y2 = 357, 204, 398, 250
cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
cv2.imshow("Detection Box", image)
cv2.waitKey(0)
cv2.destroyAllWindows()`
本段代码按理说会输出could you please fetch me the dinosaur model at the bottom对应的框。但实际上这个bbox对应的是the yellow cone对应的框。

**Comment by luyh20** [comment]
感谢你指出数据上的错误，数据集在标注过程中可能存在个别错误，后续会收集错误数据，重新上传相关文件。

**Comment by quanfeifan** [comment]
主要是我在计算iou的时候，发现很多图的iou都是0.8以上，然后突然蹦出一些iou=0的情况。很感谢作者的回复！
