### ISSUE TITLE
About the pre-training weights for FGC_GraspNet

### ISSUE THREAD

**Issue by huamo555** [luyh20/VL-Grasp#5]
Thanks for your excellent work, can you provide the pre-training weights for FGC_GraspNet?
As in line 167 of main.py ，parser.add_argument('--checkpoint_grasp_path', default='logs/checkpoint_fgc.tar', help='Model checkpoint path')

**Comment by luyh20** [comment]
OK，there are Google Drive links, [checkpoint_best_r50.pth](https://drive.google.com/file/d/1HJQKnuiG5J02PZBQJc2KsW3RozmJYH-L/view?usp=sharing) and [checkpoint_fgc.tar](https://drive.google.com/file/d/1x4e23njqi4A_S_LlZPCUHjHT9CqFPzkc/view?usp=sharing).

**Comment by huamo555** [comment]
> 好的，有 Google Drive 链接，[checkpoint_best_r50.pth](https://drive.google.com/file/d/1HJQKnuiG5J02PZBQJc2KsW3RozmJYH-L/view?usp=sharing)和[checkpoint_fgc.tar](https://drive.google.com/file/d/1x4e23njqi4A_S_LlZPCUHjHT9CqFPzkc/view?usp=sharing)。

Thanks for your reply, after your help I have successfully run the sh train_roborefit.sh file to get the trained model, but when I run the sh test_roborefit.sh file I am confused on how to import my trained model, can you advise me on how to import the model to go for the test to get the metrics in your article?

![1711352862433](https://github.com/luyh20/VL-Grasp/assets/71839287/f556b795-d4c8-47ca-957e-23ed0bd1aad3)

**Comment by huamo555** [comment]
> > 好的，有 Google Drive 链接，[checkpoint_best_r50.pth](https://drive.google.com/file/d/1HJQKnuiG5J02PZBQJc2KsW3RozmJYH-L/view?usp=sharing)和[checkpoint_fgc.tar](https://drive.google.com/file/d/1x4e23njqi4A_S_LlZPCUHjHT9CqFPzkc/view?usp=sharing)。
> 
> 感谢您的回复，在您的帮助下，我成功运行 sh train_roborefit.sh 文件来获取经过训练的模型，但是当我运行 sh test_roborefit.sh 文件时，我对如何导入经过训练的模型感到困惑，您能给我建议吗如何导入模型进行测试以获得文章中的指标？
> 
> ![1711352862433](https://private-user-images.githubusercontent.com/71839287/316424558-f556b795-d4c8-47ca-957e-23ed0bd1aad3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjA3NDAsIm5iZiI6MTcxMTUyMDQ0MCwicGF0aCI6Ii83MTgzOTI4Ny8zMTY0MjQ1NTgtZjU1NmI3OTUtZDRjOC00N2NhLTk1N2UtMjNlZDBiZDFhYWQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA2MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYTYyMWE0NTkzNDlmYTQ1NzU5NzRjN2YzMGE1ZmI3ZDI2NjVhYjJjMzRiYWU5OTMxMzc4YTU4NGI1MmNjMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KDFulwk1Y_Sajq10meX-2Zdxi491CkMfvT8sn0oE_lA)

我解决了这个问题，代码在测试时会自己调用输出路径中的checkpoint
