### ISSUE TITLE
ImportError: Could not import _ext module.

### ISSUE THREAD

**Issue by toolren** [luyh20/VL-Grasp#9]
This error occurred when I was running the file. I originally thought it was a compilation problem of cuda version, but I still reported the error after reinstalling the environment. If you have time, can you help me with some guidance.Looking forward to your reply

`WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Traceback (most recent call last):
  File "/home/scq/zzj/VL-Grasp/GraspNet/pointnet2/pointnet2_utils.py", line 26, in <module>
    import pointnet2._ext as _ext
ImportError: /home/scq/anaconda3/envs/vl_grasp/lib/python3.7/site-packages/pointnet2-0.0.0-py3.7-linux-x86_64.egg/pointnet2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    from model.FGC_graspnet import FGC_graspnet
  File "/home/scq/zzj/VL-Grasp/GraspNet/model/FGC_graspnet.py", line 21, in <module>
    from pointnet2.pointnet2_utils import CylinderQueryAndGroup
  File "/home/scq/zzj/VL-Grasp/GraspNet/pointnet2/pointnet2_utils.py", line 30, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst
`

**Comment by luyh20** [comment]
Download the pointnet2 from https://github.com/facebookresearch/votenet/tree/main/pointnet2, and remove the old version pointnet folder, install again maybe help.
